import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Navbar } from "@/components/shared/navbar";
import {
  Stethoscope,
  Calendar,
  Brain,
  Bell,
  Shield,
  Clock,
  Users,
  ChevronRight,
} from "lucide-react";

const features = [
  {
    icon: Calendar,
    title: "Smart Scheduling",
    description:
      "Real-time slot availability with conflict-free booking powered by atomic transactions.",
  },
  {
    icon: Brain,
    title: "AI-Powered Summaries",
    description:
      "Pre-visit symptom analysis and post-visit patient-friendly summaries generated by AI.",
  },
  {
    icon: Bell,
    title: "Medication Reminders",
    description:
      "Automated reminders for prescribed medications with customizable schedules.",
  },
  {
    icon: Shield,
    title: "Role-Based Access",
    description:
      "Secure access control for patients, doctors, and administrators.",
  },
  {
    icon: Clock,
    title: "Google Calendar Sync",
    description:
      "Seamlessly sync appointments with Google Calendar for both patients and doctors.",
  },
  {
    icon: Users,
    title: "Doctor Management",
    description:
      "Admin tools for managing doctor profiles, specialisations, and working hours.",
  },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-sky-50 to-white">
      <Navbar />

      {/* Hero Section */}
      <section className="container mx-auto px-4 pt-20 pb-32">
        <div className="max-w-4xl mx-auto text-center">
          <div className="inline-flex items-center gap-2 bg-sky-100 text-sky-700 px-4 py-1.5 rounded-full text-sm font-medium mb-8">
            <Stethoscope className="h-4 w-4" />
            Healthcare Made Simple
          </div>
          <h1 className="text-5xl md:text-6xl font-bold text-gray-900 mb-6 leading-tight">
            Book Appointments{" "}
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-sky-500 to-cyan-600">
              Smarter
            </span>
            , Not Harder
          </h1>
          <p className="text-xl text-gray-600 mb-10 max-w-2xl mx-auto">
            An intelligent healthcare platform with AI-powered visit
            preparation, real-time scheduling, and automated follow-up care.
          </p>
          <div className="flex items-center justify-center gap-4">
            <Link href="/register">
              <Button size="lg" className="text-base px-8 h-12">
                Get Started
                <ChevronRight className="ml-2 h-5 w-5" />
              </Button>
            </Link>
            <Link href="/login">
              <Button variant="outline" size="lg" className="text-base px-8 h-12">
                Sign In
              </Button>
            </Link>
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="container mx-auto px-4 pb-32">
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">
            Everything You Need
          </h2>
          <p className="text-gray-600 max-w-xl mx-auto">
            A comprehensive platform designed for patients, doctors, and
            administrators
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl mx-auto">
          {features.map((feature) => {
            const Icon = feature.icon;
            return (
              <Card
                key={feature.title}
                className="group hover:shadow-lg transition-all duration-300 border-gray-100 hover:border-sky-200"
              >
                <CardContent className="p-6">
                  <div className="h-12 w-12 bg-sky-100 rounded-xl flex items-center justify-center mb-4 group-hover:bg-sky-200 transition-colors">
                    <Icon className="h-6 w-6 text-sky-600" />
                  </div>
                  <h3 className="text-lg font-semibold text-gray-900 mb-2">
                    {feature.title}
                  </h3>
                  <p className="text-gray-600 text-sm leading-relaxed">
                    {feature.description}
                  </p>
                </CardContent>
              </Card>
            );
          })}
        </div>
      </section>

      {/* CTA Section */}
      <section className="bg-gradient-to-r from-sky-500 to-cyan-600 py-20">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-3xl font-bold text-white mb-4">
            Ready to Transform Your Healthcare Experience?
          </h2>
          <p className="text-sky-100 mb-8 max-w-xl mx-auto">
            Join thousands of patients and healthcare providers using our
            platform for smarter appointment management.
          </p>
          <Link href="/register">
            <Button
              size="lg"
              variant="secondary"
              className="text-base px-8 h-12"
            >
              Create Free Account
            </Button>
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t bg-white py-12">
        <div className="container mx-auto px-4 text-center text-gray-500 text-sm">
          <div className="flex items-center justify-center gap-2 mb-4">
            <Stethoscope className="h-5 w-5 text-sky-600" />
            <span className="font-semibold text-gray-700">
              Healthcare Appointment Platform
            </span>
          </div>
          <p>&copy; {new Date().getFullYear()} All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
